## Actividad 3_17: Regresión con RN. ¿Cuanto vale un portátil?
<div style="border-style:groove;border-width:thin;padding:10px">
Ya hemos hecho un ejercicio de clasificación con redes neuronales. Vamos a trabajar ahora con uno de regresión. En este caso es un dataset con datos de portátiles. 
</div>

<div style="border-style:groove;border-width:thin;padding:10px">
Debes hacer lo siguiente:
    <ol>
        <li>Carga el archivo "laptop_price.csv".</li>
        <li>Echa un vistazo a los datos. Corrige cosas si es necesario.</li>
        <li>Hay muchas columnas categóricas. Transfórmalas.</li>
        <li>Divide el dataset en conjuntos de training y de test.</li>
        <li>Soluciona el ejercicio con una red neuronal.</li>
    </ol>
</div>

In [1]:
import pandas as pd

portatiles = pd.read_csv("laptop_price.csv", sep= ",", encoding="cp1252")
portatiles.head(5)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [2]:
portatiles.isna().sum()

laptop_ID           0
Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [3]:
portatiles["Weight"] = portatiles["Weight"].str.replace("kg", "")
portatiles["Ram"] = portatiles["Ram"].str.replace("GB", "")
portatiles["Memory Type"] = portatiles["Memory"].str.split(" ", expand=True)[1]
portatiles["Memory"] = portatiles["Memory"].str.replace("GB", "").str.replace("TB", "").str.split(" ", expand=True)[0]
portatiles.drop(columns=["laptop_ID", "Product"], inplace=True)
portatiles

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Memory Type
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,SSD
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128,Intel HD Graphics 6000,macOS,1.34,898.94,Flash
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256,Intel HD Graphics 620,No OS,1.86,575.00,SSD
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512,AMD Radeon Pro 455,macOS,1.83,2537.45,SSD
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,SSD
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4,128,Intel HD Graphics 520,Windows 10,1.8,638.00,SSD
1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16,512,Intel HD Graphics 520,Windows 10,1.3,1499.00,SSD
1300,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2,64,Intel HD Graphics,Windows 10,1.5,229.00,Flash
1301,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6,1,AMD Radeon R5 M330,Windows 10,2.19,764.00,HDD
1302,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4,500,Intel HD Graphics,Windows 10,2.2,369.00,HDD

In [4]:
# Haciendo dummies de las variables categóricas, menos de weight, ram y memory, que ya son numéricas
df_dummies = pd.get_dummies(portatiles, columns=["Company", "TypeName", "OpSys", "Memory Type", "ScreenResolution", "Cpu", "Gpu", "Inches"], dtype=int)
df_dummies["Memory"] = df_dummies["Memory"].astype(float)
df_dummies["Ram"] = df_dummies["Ram"].astype(float)
df_dummies["Weight"] = df_dummies["Weight"].astype(float)
df_dummies

,Ram,Memory,Weight,Price_euros,Company_Acer,Company_Apple,Company_Asus,Company_Chuwi,Company_Dell,Company_Fujitsu,...,Inches_13.5,Inches_13.9,Inches_14.0,Inches_14.1,Inches_15.0,Inches_15.4,Inches_15.6,Inches_17.0,Inches_17.3,Inches_18.4
0,8.0,128.0,1.37,1339.69,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,8.0,128.0,1.34,898.94,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,8.0,256.0,1.86,575.00,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,16.0,512.0,1.83,2537.45,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,8.0,256.0,1.37,1803.60,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,4.0,128.0,1.80,638.00,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1299,16.0,512.0,1.30,1499.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1300,2.0,64.0,1.50,229.00,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1301,6.0,1.0,2.19,764.00,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1302,4.0,500.0,2.20,369.00,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [5]:
# Separar las variables independientes (X) de la variable dependiente (y)
X = df_dummies.drop(columns=["Price_euros"])
y = df_dummies["Price_euros"]

# Dividir el conjunto de datos en entrenamiento y prueba
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [29]:
# Entrenar un modelo de regresion con redes neuronales con Keras
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential()
model.add(keras.layers.Dense(209, activation="relu", input_shape=(X_train.shape[1],)))
model.add(keras.layers.Dense(93, activation="relu"))
model.add(keras.layers.Dense(1))
model.compile(optimizer="adam", loss="mean_squared_error",
    metrics=[
        "mae",
        keras.metrics.RootMeanSquaredError(name="rmse")
    ]
)

#history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2)

# Callback de early stopping para evitar el sobreajuste
early_stopping_cb = keras.callbacks.EarlyStopping(patience=20, restore_best_weights=True)
history = model.fit(X_train, y_train, epochs=400, validation_split=0.1, callbacks=[early_stopping_cb])

# Metrica final
y_pred = model.predict(X_test)

from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print("R2 Score:", r2)

Epoch 1/400

/home/ciabd10/anaconda3/lib/python3.13/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 1768895.2500 - mae: 1129.0636 - rmse: 1329.9982 - val_loss: 1421361.2500 - val_mae: 1032.8086 - val_rmse: 1192.2086
Epoch 2/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1667542.6250 - mae: 1092.0707 - rmse: 1291.3336 - val_loss: 1289195.0000 - val_mae: 981.9597 - val_rmse: 1135.4272
Epoch 3/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1358111.3750 - mae: 980.2969 - rmse: 1165.3804 - val_loss: 969835.7500 - val_mae: 848.3746 - val_rmse: 984.8024
Epoch 4/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 792374.1875 - mae: 726.5498 - rmse: 890.1541 - val_loss: 549163.6875 - val_mae: 592.4643 - val_rmse: 741.0558
Epoch 5/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 283473.5625 - mae: 403.3383 - rmse: 532.4224 - val_loss: 381006.5625 - val_mae: 438.9280 - val_rmse: 617.2573
Epoch 6/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 148457.9531 - mae: 292.3789 - rmse: 385.3024 - val_loss: 352508.8125 - val_mae: 401.1897 - val_rmse: 593.7245
Epoch 7/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 114591.3750 - mae: 251.1642 - rmse: 338.5135 - val_loss: 330866.7812 - val_mae: 371.8444 - val_rmse: 575.2102
Epoch 8/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 93111.9844 - mae: 221.7453 - rmse: 305.1426 - val_loss: 318803.0312 - val_mae: 356.8487 - val_rmse: 564.6265
Epoch 9/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 80148.3828 - mae: 203.7822 - rmse: 283.1049 - val_loss: 310519.8750 - val_mae: 346.4525 - val_rmse: 557.2431
Epoch 10/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 71205.0938 - mae: 188.9718 - rmse: 266.8428 - val_loss: 303865.0000 - val_mae: 338.0341 - val_rmse: 551.2395
Epoch 11/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 64006.8633 - mae: 179.1677 - rmse: 252.9958 - val_loss: 298783.0625 - val_mae: 329.9387 - val_rmse: 546.6105
Epoch 12/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 58795.8906 - mae: 171.1989 - rmse: 242.4786 - val_loss: 294552.3750 - val_mae: 323.5433 - val_rmse: 542.7268
Epoch 13/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 53955.2617 - mae: 162.1329 - rmse: 232.2827 - val_loss: 291406.0312 - val_mae: 320.5808 - val_rmse: 539.8204
Epoch 14/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 50563.0000 - mae: 155.6444 - rmse: 224.8622 - val_loss: 289065.4062 - val_mae: 315.7610 - val_rmse: 537.6480
Epoch 15/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 47484.1875 - mae: 151.1314 - rmse: 217.9087 - val_loss: 286183.5000 - val_mae: 310.8204 - val_rmse: 534.9612
Epoch 16/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 45072.7812 - mae: 146.3188 - rmse: 212.3035 - val_loss: 284131.5938 - val_mae: 306.6258 - val_rmse: 533.0400
Epoch 17/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 43231.3125 - mae: 142.3733 - rmse: 207.9214 - val_loss: 283320.1562 - val_mae: 304.9568 - val_rmse: 532.2783
Epoch 18/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 41649.0938 - mae: 139.6224 - rmse: 204.0811 - val_loss: 281161.0625 - val_mae: 301.4694 - val_rmse: 530.2462
Epoch 19/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 40183.6406 - mae: 136.0122 - rmse: 200.4586 - val_loss: 279165.3750 - val_mae: 298.3663 - val_rmse: 528.3610
Epoch 20/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 38993.4219 - mae: 133.9448 - rmse: 197.4675 - val_loss: 278729.7188 - val_mae: 296.4276 - val_rmse: 527.9486
Epoch 21/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 38061.6016 - mae: 131.7211 - rmse: 195.0938 - val_loss: 277012.8125 - val_mae: 293.4627 - val_rmse: 526.3201
Epoch 22/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 37316.9258 - mae: 130.1321 - rmse: 193.1759 - val_loss: 277852.0312 - val_mae: 294.8149 - val_rmse: 527.1167
Epoch 23/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 36737.6133 - mae: 131.2650 - rmse: 191.6706 - val_loss: 274959.7812 - val_mae: 290.5862 - val_rmse: 524.3661
Epoch 24/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 36110.1914 - mae: 127.3465 - rmse: 190.0268 - val_loss: 276053.9688 - val_mae: 291.6419 - val_rmse: 525.4084
Epoch 25/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 35162.0820 - mae: 125.6308 - rmse: 187.5155 - val_loss: 276377.7812 - val_mae: 291.9297 - val_rmse: 525.7164
Epoch 26/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 34607.0391 - mae: 126.0210 - rmse: 186.0297 - val_loss: 273822.1562 - val_mae: 287.9988 - val_rmse: 523.2802
Epoch 27/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 34601.6289 - mae: 122.8934 - rmse: 186.0151 - val_loss: 273464.6562 - val_mae: 287.5823 - val_rmse: 522.9385
Epoch 28/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 33584.3320 - mae: 122.9369 - rmse: 183.2603 - val_loss: 273286.2188 - val_mae: 287.3680 - val_rmse: 522.7678
Epoch 29/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 33148.3594 - mae: 120.6308 - rmse: 182.0669 - val_loss: 272817.2812 - val_mae: 286.9845 - val_rmse: 522.3192
Epoch 30/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 33081.3750 - mae: 122.1933 - rmse: 181.8829 - val_loss: 271666.0625 - val_mae: 285.8258 - val_rmse: 521.2159
Epoch 31/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 32737.7402 - mae: 121.6898 - rmse: 180.9357 - val_loss: 271817.7188 - val_mae: 286.9196 - val_rmse: 521.3614
Epoch 32/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 32174.2090 - mae: 118.8127 - rmse: 179.3717 - val_loss: 272580.7500 - val_mae: 289.5598 - val_rmse: 522.0927
Epoch 33/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 31713.6055 - mae: 119.2752 - rmse: 178.0831 - val_loss: 269896.8125 - val_mae: 284.5931 - val_rmse: 519.5159
Epoch 34/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 31410.3184 - mae: 117.6093 - rmse: 177.2296 - val_loss: 270156.5000 - val_mae: 284.4484 - val_rmse: 519.7658
Epoch 35/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 31179.1348 - mae: 116.4101 - rmse: 176.5761 - val_loss: 270163.0312 - val_mae: 285.0574 - val_rmse: 519.7721
Epoch 36/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 31052.1016 - mae: 115.6721 - rmse: 176.2161 - val_loss: 271488.8438 - val_mae: 288.2318 - val_rmse: 521.0459
Epoch 37/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 30533.7656 - mae: 116.0039 - rmse: 174.7391 - val_loss: 269726.4688 - val_mae: 284.9537 - val_rmse: 519.3520
Epoch 38/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 29996.4766 - mae: 113.9682 - rmse: 173.1949 - val_loss: 267675.3438 - val_mae: 282.6141 - val_rmse: 517.3735
Epoch 39/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 29973.4785 - mae: 114.4385 - rmse: 173.1285 - val_loss: 266718.3750 - val_mae: 281.9467 - val_rmse: 516.4478
Epoch 40/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 29917.2109 - mae: 112.8837 - rmse: 172.9659 - val_loss: 267705.0938 - val_mae: 284.2997 - val_rmse: 517.4023
Epoch 41/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 29381.2383 - mae: 113.1103 - rmse: 171.4096 - val_loss: 265393.4062 - val_mae: 281.0285 - val_rmse: 515.1635
Epoch 42/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 29111.8945 - mae: 112.6226 - rmse: 170.6221 - val_loss: 265959.5625 - val_mae: 281.7784 - val_rmse: 515.7126
Epoch 43/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28616.0156 - mae: 110.1261 - rmse: 169.1627 - val_loss: 265100.4688 - val_mae: 282.5761 - val_rmse: 514.8791
Epoch 44/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 28502.8184 - mae: 111.9386 - rmse: 168.8278 - val_loss: 263668.3125 - val_mae: 281.0100 - val_rmse: 513.4865
Epoch 45/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 28442.7441 - mae: 110.1142 - rmse: 168.6498 - val_loss: 264031.9688 - val_mae: 281.3619 - val_rmse: 513.8404
Epoch 46/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 27874.6309 - mae: 110.4781 - rmse: 166.9570 - val_loss: 264066.1562 - val_mae: 281.7755 - val_rmse: 513.8737
Epoch 47/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27919.4531 - mae: 109.2184 - rmse: 167.0912 - val_loss: 264874.9375 - val_mae: 283.3210 - val_rmse: 514.6600
Epoch 48/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 27578.4473 - mae: 108.3189 - rmse: 166.0676 - val_loss: 264011.0000 - val_mae: 284.0366 - val_rmse: 513.8200
Epoch 49/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 27054.9629 - mae: 108.0093 - rmse: 164.4839 - val_loss: 262884.5312 - val_mae: 282.3170 - val_rmse: 512.7227
Epoch 50/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26821.1680 - mae: 107.1863 - rmse: 163.7717 - val_loss: 260700.9219 - val_mae: 280.3023 - val_rmse: 510.5888
Epoch 51/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26993.2871 - mae: 107.4417 - rmse: 164.2963 - val_loss: 262459.3125 - val_mae: 283.3492 - val_rmse: 512.3078
Epoch 52/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26878.9941 - mae: 107.6774 - rmse: 163.9482 - val_loss: 258008.8750 - val_mae: 278.2222 - val_rmse: 507.9457
Epoch 53/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 25911.0977 - mae: 104.4092 - rmse: 160.9692 - val_loss: 262014.0625 - val_mae: 284.0469 - val_rmse: 511.8731
Epoch 54/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26861.8320 - mae: 107.7153 - rmse: 163.8958 - val_loss: 257273.7656 - val_mae: 277.8582 - val_rmse: 507.2216
Epoch 55/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 25925.3027 - mae: 106.4891 - rmse: 161.0134 - val_loss: 259133.5312 - val_mae: 280.7149 - val_rmse: 509.0516
Epoch 56/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 25474.3750 - mae: 104.3713 - rmse: 159.6069 - val_loss: 255761.1094 - val_mae: 277.2178 - val_rmse: 505.7283
Epoch 57/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 25944.1914 - mae: 106.1838 - rmse: 161.0720 - val_loss: 254599.7188 - val_mae: 278.0492 - val_rmse: 504.5788
Epoch 58/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 25912.9590 - mae: 104.6940 - rmse: 160.9750 - val_loss: 257310.7031 - val_mae: 281.3270 - val_rmse: 507.2580
Epoch 59/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 25975.5156 - mae: 105.0225 - rmse: 161.1692 - val_loss: 253126.0000 - val_mae: 276.3214 - val_rmse: 503.1163
Epoch 60/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 24896.7109 - mae: 103.0218 - rmse: 157.7869 - val_loss: 253885.6562 - val_mae: 277.9168 - val_rmse: 503.8707
Epoch 61/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 24935.0078 - mae: 102.6350 - rmse: 157.9082 - val_loss: 252494.3125 - val_mae: 277.4397 - val_rmse: 502.4881
Epoch 62/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24516.8242 - mae: 102.1643 - rmse: 156.5785 - val_loss: 252345.7500 - val_mae: 277.5026 - val_rmse: 502.3403
Epoch 63/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24202.9258 - mae: 100.2667 - rmse: 155.5729 - val_loss: 254569.9375 - val_mae: 280.5161 - val_rmse: 504.5493
Epoch 64/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 23876.8730 - mae: 99.5094 - rmse: 154.5214 - val_loss: 254055.1250 - val_mae: 280.6060 - val_rmse: 504.0388
Epoch 65/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 24218.5020 - mae: 101.2800 - rmse: 155.6230 - val_loss: 252178.8906 - val_mae: 279.7544 - val_rmse: 502.1742
Epoch 66/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 23465.3516 - mae: 99.6574 - rmse: 153.1841 - val_loss: 248879.8281 - val_mae: 276.2248 - val_rmse: 498.8786
Epoch 67/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 23431.7207 - mae: 98.5757 - rmse: 153.0742 - val_loss: 249599.5625 - val_mae: 276.9245 - val_rmse: 499.5994
Epoch 68/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23159.6172 - mae: 98.2538 - rmse: 152.1828 - val_loss: 248302.2500 - val_mae: 276.3723 - val_rmse: 498.2993
Epoch 69/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 23153.4648 - mae: 98.5239 - rmse: 152.1626 - val_loss: 247689.5938 - val_mae: 276.0256 - val_rmse: 497.6842
Epoch 70/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 22753.3594 - mae: 96.8805 - rmse: 150.8422 - val_loss: 247576.1719 - val_mae: 276.9747 - val_rmse: 497.5703
Epoch 71/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22617.3242 - mae: 96.1275 - rmse: 150.3906 - val_loss: 245388.9375 - val_mae: 275.6504 - val_rmse: 495.3675
Epoch 72/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 22497.4902 - mae: 96.1234 - rmse: 149.9916 - val_loss: 243345.0312 - val_mae: 274.2408 - val_rmse: 493.3001
Epoch 73/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 22326.2617 - mae: 94.6486 - rmse: 149.4198 - val_loss: 243348.5938 - val_mae: 274.7327 - val_rmse: 493.3037
Epoch 74/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 22086.6758 - mae: 95.7069 - rmse: 148.6159 - val_loss: 240193.1250 - val_mae: 273.7708 - val_rmse: 490.0950
Epoch 75/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22092.4531 - mae: 95.2302 - rmse: 148.6353 - val_loss: 240996.3125 - val_mae: 274.0649 - val_rmse: 490.9138
Epoch 76/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21885.4414 - mae: 94.1624 - rmse: 147.9373 - val_loss: 239087.3281 - val_mae: 272.5209 - val_rmse: 488.9656
Epoch 77/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21875.0898 - mae: 94.1784 - rmse: 147.9023 - val_loss: 236874.2656 - val_mae: 272.0676 - val_rmse: 486.6973
Epoch 78/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21702.7148 - mae: 93.4183 - rmse: 147.3184 - val_loss: 239162.9531 - val_mae: 275.4201 - val_rmse: 489.0429
Epoch 79/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21309.4629 - mae: 94.1359 - rmse: 145.9776 - val_loss: 234657.2031 - val_mae: 270.8953 - val_rmse: 484.4143
Epoch 80/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21166.7559 - mae: 92.0748 - rmse: 145.4880 - val_loss: 234745.0625 - val_mae: 271.4725 - val_rmse: 484.5050
Epoch 81/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20883.6523 - mae: 91.8010 - rmse: 144.5118 - val_loss: 233598.2500 - val_mae: 271.2231 - val_rmse: 483.3200
Epoch 82/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20980.7578 - mae: 91.1599 - rmse: 144.8474 - val_loss: 232128.3594 - val_mae: 271.1628 - val_rmse: 481.7970
Epoch 83/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21286.2715 - mae: 92.9914 - rmse: 145.8981 - val_loss: 231418.5312 - val_mae: 269.9531 - val_rmse: 481.0598
Epoch 84/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21236.5977 - mae: 93.0516 - rmse: 145.7278 - val_loss: 231192.2344 - val_mae: 273.2928 - val_rmse: 480.8245
Epoch 85/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21455.0859 - mae: 93.1408 - rmse: 146.4755 - val_loss: 232007.7969 - val_mae: 274.5732 - val_rmse: 481.6719
Epoch 86/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20649.9785 - mae: 91.4073 - rmse: 143.7010 - val_loss: 225629.5000 - val_mae: 266.4160 - val_rmse: 475.0047
Epoch 87/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20687.4004 - mae: 91.4075 - rmse: 143.8311 - val_loss: 227505.4062 - val_mae: 271.0446 - val_rmse: 476.9753
Epoch 88/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20392.6035 - mae: 89.9051 - rmse: 142.8027 - val_loss: 225385.5938 - val_mae: 269.5929 - val_rmse: 474.7479
Epoch 89/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20014.2520 - mae: 89.5843 - rmse: 141.4717 - val_loss: 224358.2812 - val_mae: 268.6733 - val_rmse: 473.6647
Epoch 90/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20061.6230 - mae: 89.0090 - rmse: 141.6391 - val_loss: 223556.1562 - val_mae: 268.8168 - val_rmse: 472.8173
Epoch 91/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19729.3516 - mae: 88.0293 - rmse: 140.4612 - val_loss: 221388.5312 - val_mae: 266.9862 - val_rmse: 470.5194
Epoch 92/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19274.4902 - mae: 86.5322 - rmse: 138.8326 - val_loss: 222494.8594 - val_mae: 270.0285 - val_rmse: 471.6936
Epoch 93/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19954.1602 - mae: 89.2001 - rmse: 141.2592 - val_loss: 216722.3750 - val_mae: 264.2614 - val_rmse: 465.5345
Epoch 94/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19351.5117 - mae: 87.4514 - rmse: 139.1097 - val_loss: 217607.6250 - val_mae: 267.0844 - val_rmse: 466.4843
Epoch 95/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19263.2930 - mae: 86.4810 - rmse: 138.7923 - val_loss: 216719.2188 - val_mae: 266.1716 - val_rmse: 465.5311
Epoch 96/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18985.4277 - mae: 86.4184 - rmse: 137.7876 - val_loss: 215119.8125 - val_mae: 265.4883 - val_rmse: 463.8101
Epoch 97/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18789.0938 - mae: 86.3082 - rmse: 137.0733 - val_loss: 211483.5312 - val_mae: 263.4662 - val_rmse: 459.8734
Epoch 98/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18601.8262 - mae: 85.0773 - rmse: 136.3885 - val_loss: 210832.0938 - val_mae: 263.3923 - val_rmse: 459.1646
Epoch 99/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18391.7344 - mae: 84.2626 - rmse: 135.6161 - val_loss: 208668.4531 - val_mae: 261.4705 - val_rmse: 456.8024
Epoch 100/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18520.0039 - mae: 84.3783 - rmse: 136.0882 - val_loss: 206959.2500 - val_mae: 261.6916 - val_rmse: 454.9277
Epoch 101/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18345.7031 - mae: 84.9279 - rmse: 135.4463 - val_loss: 204768.1719 - val_mae: 259.2188 - val_rmse: 452.5132
Epoch 102/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18344.6699 - mae: 83.9716 - rmse: 135.4425 - val_loss: 205126.6094 - val_mae: 261.3464 - val_rmse: 452.9091
Epoch 103/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18142.3066 - mae: 84.0222 - rmse: 134.6934 - val_loss: 208975.1094 - val_mae: 268.0156 - val_rmse: 457.1379
Epoch 104/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18575.4609 - mae: 84.7509 - rmse: 136.2918 - val_loss: 208154.0625 - val_mae: 268.5582 - val_rmse: 456.2390
Epoch 105/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18039.9336 - mae: 84.9782 - rmse: 134.3128 - val_loss: 199504.9219 - val_mae: 258.1135 - val_rmse: 446.6597
Epoch 106/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17962.5078 - mae: 83.7564 - rmse: 134.0243 - val_loss: 200994.2344 - val_mae: 262.6811 - val_rmse: 448.3238
Epoch 107/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17719.7871 - mae: 83.5295 - rmse: 133.1157 - val_loss: 195576.2031 - val_mae: 255.4313 - val_rmse: 442.2400
Epoch 108/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18354.7832 - mae: 84.7637 - rmse: 135.4798 - val_loss: 193578.1719 - val_mae: 255.2536 - val_rmse: 439.9752
Epoch 109/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17983.9688 - mae: 83.9339 - rmse: 134.1043 - val_loss: 191852.4062 - val_mae: 252.3951 - val_rmse: 438.0096
Epoch 110/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17560.3887 - mae: 82.4522 - rmse: 132.5156 - val_loss: 193185.6875 - val_mae: 257.2922 - val_rmse: 439.5289
Epoch 111/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17321.2617 - mae: 82.2939 - rmse: 131.6103 - val_loss: 192209.3750 - val_mae: 255.0895 - val_rmse: 438.4169
Epoch 112/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17288.6387 - mae: 81.6645 - rmse: 131.4863 - val_loss: 191840.0625 - val_mae: 256.7662 - val_rmse: 437.9955
Epoch 113/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17127.9004 - mae: 81.3914 - rmse: 130.8736 - val_loss: 187245.2344 - val_mae: 253.2916 - val_rmse: 432.7184
Epoch 114/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16862.0879 - mae: 80.8702 - rmse: 129.8541 - val_loss: 185929.3125 - val_mae: 252.7568 - val_rmse: 431.1952
Epoch 115/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16737.2734 - mae: 78.8452 - rmse: 129.3726 - val_loss: 188862.3438 - val_mae: 257.4898 - val_rmse: 434.5829
Epoch 116/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16500.4668 - mae: 79.7252 - rmse: 128.4541 - val_loss: 184289.6406 - val_mae: 253.3003 - val_rmse: 429.2897
Epoch 117/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16441.6641 - mae: 79.4845 - rmse: 128.2251 - val_loss: 181738.5781 - val_mae: 250.8259 - val_rmse: 426.3081
Epoch 118/400
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16406.5078 - mae: 78.9305 - rmse: 128.0879 - val_loss: 178359.8906 - val_mae: 249.2677 - val_rmse: 422.3268
Epoch 119/400